---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hasmissingsvcaccount
    namespace: conftest
  spec:
    template:
      spec:
        serviceAccountName: foo