---
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
spec:
  readiness:
    statsEnabled: true
  sync:
    syncOnly:
      - version: "v1"
        group: ""
        kind: "Namespace"
      - version: "v1"
        group: ""
        kind: "ServiceAccount"
      - version: "v1"
        group: ""
        kind: "PersistentVolumeClaim"
      - version: "v1"
        group: "networking.k8s.io"
        kind: "NetworkPolicy"
      - version: "v1"
        group: ""
        kind: "Service"
      - version: "v1"
        group: "monitoring.coreos.com"
        kind: "ServiceMonitor"
      - version: "v1"
        group: "apps"
        kind: "Deployment"
      - version: "v1"
        group: "policy"
        kind: "PodDisruptionBudget"