---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: secretenvvars
  spec:
    template:
      spec:
        containers:
          - name: bar
            env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: token
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: secretenvvars
  spec:
    template:
      spec:
        containers:
          - name: bar
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: my-secret
                    key: token