---
apiVersion: v1
kind: List
metadata:
  name: Foo
items:
# Cluster Scoped
- apiVersion: v1
  kind: SecurityContextConstraints
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
    name: Bar
# Project Scoped
- apiVersion: v1
  kind: ProjectRequest
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
    name: Bar
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
    name: Bar
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
    name: Bar
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
    name: Bar
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
    name: Bar
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
    name: Bar