---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: triggercontainernamemissmatch
spec:
  template:
    spec:
      containers:
        - name: bar
        - name: foo
  triggers:
    - type: ImageChange
      imageChangeParams:
        containerNames:
          - foobar
          - foo
          - bar