---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: hasmissingsvcmon
    labels:
      app.kubernetes.io/name: Foo-hasmissingsvcmon
      app.kubernetes.io/instance: Bar-hasmissingsvcmon
      app.kubernetes.io/version: v1
      app.kubernetes.io/component: FooBar-hasmissingsvcmon
      app.kubernetes.io/part-of: Foo-hasmissingsvcmon
      app.kubernetes.io/managed-by: Bar-hasmissingsvcmon
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
    selector:
      app.kubernetes.io/name: Foo-hasmissingsvcmon
      app.kubernetes.io/instance: Bar-hasmissingsvcmon
      app.kubernetes.io/version: v1
      app.kubernetes.io/component: FooBar-hasmissingsvcmon
      app.kubernetes.io/part-of: Foo-hasmissingsvcmon
      app.kubernetes.io/managed-by: Bar-hasmissingsvcmon
