---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: HasMissingSvcMon
  spec:
    ports:
      - port: 8080
        targetPort: 8080
      - name: metrics
        port: 9779
        targetPort: 9779
    selector:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
- apiVersion: v1
  kind: Service
  metadata:
    name: HasSvcMonWithIncorrectLabels
  spec:
    ports:
      - port: 8080
        targetPort: 8080
      - name: metrics
        port: 9779
        targetPort: 9779
    selector:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: MissingSelectorLabels
  spec:
    selector:
      matchLabels:
        app: Foo
    endpoints:
      - port: metrics
        interval: 15s