---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hostnetworkisset
  spec:
    template:
      spec:
        hostNetwork: "true"
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: hostnetworkisset
  spec:
    template:
      spec:
        hostNetwork: "true"