---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
    name: replicaiseven
  spec:
    replicas: 2
    selector:
      matchLabels:
        app.kubernetes.io/name: Foo
        app.kubernetes.io/instance: Bar
        app.kubernetes.io/component: FooBar
        app.kubernetes.io/part-of: Foo
        app.kubernetes.io/managed-by: Bar
    template:
      metadata:
        labels:
          app.kubernetes.io/name: Foo
          app.kubernetes.io/instance: Bar
          app.kubernetes.io/component: FooBar
          app.kubernetes.io/part-of: Foo
          app.kubernetes.io/managed-by: Bar
      spec:
        containers:
          - name: bar
            image: quay.io/redhat-cop/openshift-applier@sha256:8a99a0105f85e350bff43802b204b5ce2a501cad1aa7df5253638ced1d108957
            env:
              - name: CONTAINER_MAX_MEMORY
                valueFrom:
                  resourceFieldRef:
                    resource: limits.memory
            livenessProbe:
              exec:
                command:
                  - /bin/bash
                  - '-c'
                  - /opt/eap/bin/livenessProbe.sh
              failureThreshold: 3
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            readinessProbe:
              exec:
                command:
                  - /bin/bash
                  - '-c'
                  - /opt/eap/bin/readinessProbe.sh
              failureThreshold: 3
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 2Gi
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
    name: replicaiseven
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app.kubernetes.io/name: Foo
          app.kubernetes.io/instance: Bar
          app.kubernetes.io/component: FooBar
          app.kubernetes.io/part-of: Foo
          app.kubernetes.io/managed-by: Bar
      spec:
        containers:
          - name: bar
            image: quay.io/redhat-cop/openshift-applier@sha256:8a99a0105f85e350bff43802b204b5ce2a501cad1aa7df5253638ced1d108957
            env:
              - name: CONTAINER_MAX_MEMORY
                valueFrom:
                  resourceFieldRef:
                    resource: limits.memory
            livenessProbe:
              exec:
                command:
                  - /bin/bash
                  - '-c'
                  - /opt/eap/bin/livenessProbe.sh
              failureThreshold: 3
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            readinessProbe:
              exec:
                command:
                  - /bin/bash
                  - '-c'
                  - /opt/eap/bin/readinessProbe.sh
              failureThreshold: 3
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 2Gi
    triggers:
      - type: ConfigChange