---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: memorylimittoolarge
  spec:
    template:
      spec:
        containers:
          - name: bar
            resources:
              limits:
                memory: 7Gi
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: memorylimittoolarge
  spec:
    template:
      spec:
        containers:
          - name: bar
            resources:
              limits:
                memory: 7Gi
