---
apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
    name: NoTriggers
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          app.kubernetes.io/name: Foo
          app.kubernetes.io/instance: Bar
          app.kubernetes.io/component: FooBar
          app.kubernetes.io/part-of: Foo
          app.kubernetes.io/managed-by: Bar