---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: HasMissingSvcAccount
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          app.kubernetes.io/name: Foo
          app.kubernetes.io/instance: Bar
          app.kubernetes.io/component: FooBar
          app.kubernetes.io/part-of: Foo
          app.kubernetes.io/managed-by: Bar
    serviceAccountName: missing
- apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    name: ShouldNotFire
  spec:
    minAvailable: 2
    selector:
      matchLabels:
        app.kubernetes.io/name: Foo
        app.kubernetes.io/instance: Bar
        app.kubernetes.io/component: FooBar
        app.kubernetes.io/part-of: Foo
        app.kubernetes.io/managed-by: Bar
- apiVersion: v1
  kind: Service
  metadata:
    name: ShouldNotFire
  spec:
    ports:
      - port: 8080
        targetPort: 8080
      - name: metrics
        port: 9779
        targetPort: 9779
    selector:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: ShouldNotFire
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: Foo
        app.kubernetes.io/instance: Bar
        app.kubernetes.io/component: FooBar
        app.kubernetes.io/part-of: Foo
        app.kubernetes.io/managed-by: Bar
    endpoints:
      - port: metrics
        interval: 15s