---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: replicaiseven
  spec:
    replicas: 2
    template:
      spec:
        containers:
          - name: bar
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: replicaiseven
  spec:
    replicas: 2
    template:
      spec:
        containers:
          - name: bar