---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
      redhat-cop.github.com/team: rego-polices
      app: Foo
    name: nonestandardlabel
  spec:
    template:
      spec:
        containers:
          - name: bar
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
      redhat-cop.github.com/team: rego-polices
      app: Foo
    name: nonestandardlabel
  spec:
    template:
      spec:
        containers:
          - name: bar
