---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: podantiaffinitynotset
  spec:
    affinity:
      bob: lbha
    template:
      spec:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: podantiaffinitynotset
  spec:
    affinity:
      bob: lbha
    template:
      spec:
