---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: noproblivenessset
  spec:
    template:
      spec:
        containers:
        - name: bar
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/livenessProbe.sh
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: noproblivenessset
  spec:
    template:
      spec:
        containers:
          - name: bar
            readinessProbe:
              exec:
                command:
                  - /bin/bash
                  - '-c'
                  - /opt/eap/bin/livenessProbe.sh
              failureThreshold: 3
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1