---
apiVersion: v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: Foo
    app.kubernetes.io/instance: Bar
    app.kubernetes.io/component: FooBar
    app.kubernetes.io/part-of: Foo
    app.kubernetes.io/managed-by: Bar
  name: bar
