---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hasmissingpvc
    namespace: conftest
  spec:
    template:
      spec:
        volumes:
          - name: my-pvc
            persistentVolumeClaim:
              claimName: FooBar
