---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: resourcelimitsmemorynotset
  spec:
    template:
      spec:
        containers:
          - name: bar
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: resourcelimitsmemorynotset
  spec:
    template:
      spec:
        containers:
          - name: bar
            resources:
              requests:
                memory: 100Mi
                cpu: 100m