---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: hasmissingsvcmon
  spec:
    selector:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
- apiVersion: v1
  kind: Service
  metadata:
    name: hassvcmonwithincorrectlabels
  spec:
    selector:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/instance: Bar
      app.kubernetes.io/component: FooBar
      app.kubernetes.io/part-of: Foo
      app.kubernetes.io/managed-by: Bar
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: missingselectorlabels
  spec:
    selector:
      matchLabels:
        app: Foo