apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: bar
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      app.kubernetes.io/name: Foo-hasmissingpdb
      app.kubernetes.io/instance: Bar-hasmissingpdb
      app.kubernetes.io/version: v1
      app.kubernetes.io/component: FooBar-hasmissingpdb
      app.kubernetes.io/part-of: Foo-hasmissingpdb
      app.kubernetes.io/managed-by: Bar-hasmissingpdb
    name: shouldneverfire-pdb
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: Foo-hasmissingpdb
        app.kubernetes.io/instance: Bar-hasmissingpdb
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: FooBar-hasmissingpdb
        app.kubernetes.io/part-of: Foo-hasmissingpdb
        app.kubernetes.io/managed-by: Bar-hasmissingpdb
    endpoints:
      - port: 8080-tcp
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/name: Foo-hasmissingpdb
      app.kubernetes.io/instance: Bar-hasmissingpdb
      app.kubernetes.io/version: v1
      app.kubernetes.io/component: FooBar-hasmissingpdb
      app.kubernetes.io/part-of: Foo-hasmissingpdb
      app.kubernetes.io/managed-by: Bar-hasmissingpdb
    name: shouldneverfire-pdb
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
    selector:
      app.kubernetes.io/name: Foo-hasmissingpdb
      app.kubernetes.io/instance: Bar-hasmissingpdb
      app.kubernetes.io/version: v1
      app.kubernetes.io/component: FooBar-hasmissingpdb
      app.kubernetes.io/part-of: Foo-hasmissingpdb
      app.kubernetes.io/managed-by: Bar-hasmissingpdb
- apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    name: shouldneverfire-svc
  spec:
    minAvailable: 2
    selector:
      matchLabels:
        app.kubernetes.io/name: Foo-hasmissingsvc
        app.kubernetes.io/instance: Bar-hasmissingsvc
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: FooBar-hasmissingsvc
        app.kubernetes.io/part-of: Foo-hasmissingsvc
        app.kubernetes.io/managed-by: Bar-hasmissingsvc