name: Run pre-commit

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=open-policy-agent/opa
      OPA_VERSION: v1.15.2
      # renovate: datasource=github-releases depName=StyraInc/regal
      REGAL_VERSION: v0.40.0
      # renovate: datasource=github-releases depName=plexsystems/konstraint
      KONSTRAINT_VERSION: v0.43.0
    name: pre-commit
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.x

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0

      - name: Setup konstraint
        run: go install github.com/plexsystems/konstraint@${KONSTRAINT_VERSION}

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@950f159a49aa91f9323f36f1de81c7f6b5de9576 # v2.3.0
        with:
          version: ${{ env.OPA_VERSION }}

      - name: Setup Regal
        uses: StyraInc/setup-regal@33a142b1189004e0f14bf42b15972c67eecce776 # v1.0.0
        with:
          version: ${{ env.REGAL_VERSION }}

      - name: Remove rh-pre-commit hook (requires VPN)
        uses: mikefarah/yq@0f4fb8d35ec1a939d78dd6862f494d19ec589f19 # v4.52.5
        with:
          cmd: yq -i 'del( .repos[] | select(.rev == "rh-pre-commit-*"))' .pre-commit-config.yaml

      - uses: garethahealy/pre-commit-action@9638b5f3212a29c34d088fd7d239a62061ea621c # v4.5.1-1

      - name: Check if there are changes
        id: changes
        run: |
          git checkout HEAD -- .pre-commit-config.yaml
          echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Fail if changes found
        if: steps.changes.outputs.changed >= 1
        run: |
          echo "Uncommitted changes exist. Failing."
          echo
          git status --porcelain
          exit 1

      - name: Link checker
        uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # 1.0.17
